""" Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""


def next_fib(i, j):
    return i + j


i = 1
j = 2
flag = True
sum = 2
max_num = 4000000

while flag:
    temp = next_fib(i, j)
    i = j
    j = temp

    if j > max_num:
        flag = False
    elif j % 2 == 0:
        sum += j

print("Result: ")
print(sum)
